apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nikhil-999/frontend:latest  # Replace with your GCP project ID
        ports:
        - containerPort: 3000  # Match with the exposed port in your Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000  # Forward traffic to the container port
  selector:
    app: frontend

